feat(dropdown): Add multi selection example
adevinta/spark-android pull request #1181
Opened 2024-06-20 07:37 UTC by soulcramer

## 📋 Changes

Add multi selection example
Also add the missing padding in the dropdown menu

## 🤔 Context

Closes #1162 

## ✅ Checklist

- [x] I have reviewed the submitted code.
- [x] I have tested on a phone device/emulator.

2024-06-25 09:45 UTC, kazaky commented on catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/text/DropdownExamples.kt
> +                                    // expanded = false
I would suggest to extract this part, to make the example more concise, easy to go through the code

2024-06-25 09:49 UTC, kazaky requested changes
kindly check the comment

2024-06-25 13:42 UTC, kazaky approved these changes

2024-06-26 14:04 UTC, merged

2024-06-27 07:58 UTC, soulcramer commented
@kazaky Please don't merge PR's if they're not based on `main` otherwise it'll break the branch chain