chore: Update color tokens
adevinta/spark-android pull request #151
Opened 2023-02-27 17:21 UTC by MarinaRomanova

## 🧑‍ Changes description
Update color tokens for Spark Theme

## 🤔 Context
Color tokens have changed

2023-02-27 17:22 UTC, SimonMarquis commented on spark/src/main/kotlin/com/adevinta/spark/tokens/Color.kt
> + *  * contrast is not required.
```suggestion
 * contrast is not required.
```

2023-02-27 17:29 UTC, SimonMarquis submitted a review, later dismissed
LGTM

2023-02-27 17:40 UTC, soulcramer requested changes

2023-02-27 17:40 UTC, soulcramer commented on spark/src/main/kotlin/com/adevinta/spark/tokens/Color.kt
>      inverseSurface: Color = Grey20,
This should be removed then
```suggestion

```

2023-02-27 17:40 UTC, soulcramer commented on spark/src/main/kotlin/com/adevinta/spark/tokens/Color.kt
>      inverseOnSurface: Color = Grey95,
This should be removed then
```suggestion

```

2023-02-27 17:40 UTC, soulcramer commented on spark/src/main/kotlin/com/adevinta/spark/tokens/Color.kt
> +    overlay: Color = Surfer80.copy(alpha = 0.75f),
We can remove this as on Android the is handled by the OS
```suggestion

```

2023-02-27 17:40 UTC, soulcramer commented on spark/src/main/kotlin/com/adevinta/spark/tokens/Color.kt
>   * sit on top of other surfaces with [surface] color.
We should remove these as well

2023-02-27 17:40 UTC, soulcramer commented on spark/src/main/kotlin/com/adevinta/spark/tokens/Color.kt
> +    @Deprecated("This property will be removed as it is not part of Spark Token")
We can remove the Deprecated on this one as it's necessary for Material

2023-02-28 14:57 UTC, SimonMarquis approved these changes

2023-02-28 15:49 UTC, merged