fix: merge descendants of Tag for UI tests
adevinta/spark-android pull request #511
Opened 2023-07-06 16:13 UTC by ThibaultChariere

## 📋 Changes description

Added a semantic on the Spark Tag to merge the descendant nodes for UI tests.

## 🤔 Context

When UI testing a `TagTinted` component, there was an issue trying to find the text inside of it. Indeed we need to merge the descendants of this composable to access the text inside.

## ✅ Checklist

- [ ] Link to GitHub issues it solves. 
- [ ] I have reviewed the submitted code.
- [ ] I have tested on a phone device/emulator.
- [ ] If it includes design changes, please ask for a review `spark-design` GitHub team.

## 🗒️ Other info

Validated with @soulcramer 

[Contributing](https://github.com/adevinta/spark-android/blob/main/docs/contributing.md) has more information and tips for a great pull request.

2023-07-06 17:36 UTC, MarinaRomanova requested changes
Could you add var name please

2023-07-06 22:02 UTC, soulcramer commented
What do you mean by var name?

2023-07-06 22:03 UTC, soulcramer commented
LGTM but we'll need to add a unit test for this as well

2023-07-07 08:07 UTC, SimonMarquis commented on spark/src/main/kotlin/com/adevinta/spark/components/tags/Tag.kt
> +            .semantics(true) {}
```suggestion
            .semantics(mergeDescendants = true) {}
```

2023-07-07 09:20 UTC, MarinaRomanova approved these changes

2023-07-07 12:16 UTC, merged